on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-lastest

    steps:
    - uses: actions/checkout@main

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with: 
        dotnet-version: '6.0.x'